//
// Door.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Door: Codable {

    public var _id: Int64
    public var x1: Float
    public var y1: Float
    public var x2: Float
    public var y2: Float
    public var width: Float
    public var wall1Id: Int64
    public var wall2Id: Int64
    public var room1Id: Int64
    public var room2Id: Int64

    public init(_id: Int64, x1: Float, y1: Float, x2: Float, y2: Float, width: Float, wall1Id: Int64, wall2Id: Int64, room1Id: Int64, room2Id: Int64) {
        self._id = _id
        self.x1 = x1
        self.y1 = y1
        self.x2 = x2
        self.y2 = y2
        self.width = width
        self.wall1Id = wall1Id
        self.wall2Id = wall2Id
        self.room1Id = room1Id
        self.room2Id = room2Id
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case x1
        case y1
        case x2
        case y2
        case width
        case wall1Id = "wall1_id"
        case wall2Id = "wall2_id"
        case room1Id = "room1_id"
        case room2Id = "room2_id"
    }

}
