//
// Elevator.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Elevator: Codable {

    public var _id: Int64
    public var x: Float
    public var y: Float
    public var direction: Float
    public var wallId: Int64?
    public var elevatorUpId: Int64?
    public var elevatorDownId: Int64?

    public init(_id: Int64, x: Float, y: Float, direction: Float, wallId: Int64? = nil, elevatorUpId: Int64? = nil, elevatorDownId: Int64? = nil) {
        self._id = _id
        self.x = x
        self.y = y
        self.direction = direction
        self.wallId = wallId
        self.elevatorUpId = elevatorUpId
        self.elevatorDownId = elevatorDownId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case x
        case y
        case direction
        case wallId = "wall_id"
        case elevatorUpId = "elevator_up_id"
        case elevatorDownId = "elevator_down_id"
    }

}
