//
// Floor.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Floor: Codable {

    public var _id: Int64
    public var name: String
    public var rooms: [Room]?
    public var doors: [Door]?

    public init(_id: Int64, name: String, rooms: [Room]? = nil, doors: [Door]? = nil) {
        self._id = _id
        self.name = name
        self.rooms = rooms
        self.doors = doors
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case rooms
        case doors
    }

}
