//
// Furniture.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Furniture: Codable {

    public var _id: Int64
    public var name: String?
    public var x1: Float
    public var y1: Float
    public var x2: Float
    public var y2: Float

    public init(_id: Int64, name: String? = nil, x1: Float, y1: Float, x2: Float, y2: Float) {
        self._id = _id
        self.name = name
        self.x1 = x1
        self.y1 = y1
        self.x2 = x2
        self.y2 = y2
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case x1
        case y1
        case x2
        case y2
    }

}
