//
// GraphEdge.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GraphEdge: Codable {

    public var _id: Int64
    public var node1Id: Int64
    public var node2Id: Int64
    public var weight: Float

    public init(_id: Int64, node1Id: Int64, node2Id: Int64, weight: Float) {
        self._id = _id
        self.node1Id = node1Id
        self.node2Id = node2Id
        self.weight = weight
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case node1Id = "node1_id"
        case node2Id = "node2_id"
        case weight
    }

}
