//
// GraphNode.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GraphNode: Codable {

    public enum ObjType: String, Codable { 
        case inRoom = "in_room"
        case door = "door"
        case staircase = "staircase"
        case elevator = "elevator"
        case qr = "qr"
    }
    public var _id: Int64
    public var x: Float
    public var y: Float
    public var z: Float
    public var direction: Float?
    public var objId: Int64
    public var objType: ObjType

    public init(_id: Int64, x: Float, y: Float, z: Float, direction: Float? = nil, objId: Int64, objType: ObjType) {
        self._id = _id
        self.x = x
        self.y = y
        self.z = z
        self.direction = direction
        self.objId = objId
        self.objType = objType
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case x
        case y
        case z
        case direction
        case objId = "obj_id"
        case objType = "obj_type"
    }

}
