//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var _id: Int64?
    public var name: String?
    public var _description: String?
    public var address: String?

    public init(_id: Int64? = nil, name: String? = nil, _description: String? = nil, address: String? = nil) {
        self._id = _id
        self.name = name
        self._description = _description
        self.address = address
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case address
    }

}
