//
// Room.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Room: Codable {

    public var _id: Int64
    public var name: String
    public var _description: String
    public var canSearch: Bool
    public var walls: [Wall]
    public var elevators: [Elevator]?
    public var staircases: [Staircase]?
    public var furniture: [Furniture]?
    public var qrs: [QR]?

    public init(_id: Int64, name: String, _description: String, canSearch: Bool, walls: [Wall], elevators: [Elevator]? = nil, staircases: [Staircase]? = nil, furniture: [Furniture]? = nil, qrs: [QR]? = nil) {
        self._id = _id
        self.name = name
        self._description = _description
        self.canSearch = canSearch
        self.walls = walls
        self.elevators = elevators
        self.staircases = staircases
        self.furniture = furniture
        self.qrs = qrs
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case canSearch = "can_search"
        case walls
        case elevators
        case staircases
        case furniture
        case qrs
    }

}
