//
// Scheme.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Scheme: Codable {

    public var _id: Int64
    public var name: String
    public var _description: String
    public var address: String
    public var floors: [Floor]?
    public var graph: SchemeGraph?

    public init(_id: Int64, name: String, _description: String, address: String, floors: [Floor]? = nil, graph: SchemeGraph? = nil) {
        self._id = _id
        self.name = name
        self._description = _description
        self.address = address
        self.floors = floors
        self.graph = graph
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case _description = "description"
        case address
        case floors
        case graph
    }

}
