//
// Staircase.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Staircase: Codable {

    public var _id: Int64
    public var x: Float
    public var y: Float
    public var width: Float
    public var height: Float
    public var direction: Float
    public var staircaseUpId: Int64?
    public var staircaseDownId: Int64?

    public init(_id: Int64, x: Float, y: Float, width: Float, height: Float, direction: Float, staircaseUpId: Int64? = nil, staircaseDownId: Int64? = nil) {
        self._id = _id
        self.x = x
        self.y = y
        self.width = width
        self.height = height
        self.direction = direction
        self.staircaseUpId = staircaseUpId
        self.staircaseDownId = staircaseDownId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case x
        case y
        case width
        case height
        case direction
        case staircaseUpId = "staircase_up_id"
        case staircaseDownId = "staircase_down_id"
    }

}
